# fly.toml app configuration file generated for econo-list on 2023-09-14T01:47:16-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "econo-list"
primary_region = "gru"

[build]

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
